#!/usr/bin/env python3
"""
Phone OSINT Investigator v3 — Advanced Internet Scraper
RAVEN Cybersecurity | For legal defensive/investigative use only

Usage:
    python phone_osint_v3.py +31645161166
    python phone_osint_v3.py +31645161166 --delay 2 --output ./reports

What it does:
    - Generates 30+ Google/Bing/DDG dork queries across multiple number formats
    - Scrapes phone reputation databases (Truecaller, WhoCalledMe, SpamCalls, etc.)
    - Searches paste sites (Pastebin, Ghostbin, Rentry, etc.)
    - Searches public forums (Reddit)
    - Checks social media presence (WhatsApp, Telegram, etc.)
    - Outputs a full dark-themed HTML evidence report + JSON dump
"""

import sys
import json
import time
import asyncio
import argparse
import datetime
import urllib.parse
import re
import os
from dataclasses import dataclass, field, asdict
from typing import Optional

import requests
from bs4 import BeautifulSoup
import phonenumbers
from phonenumbers import geocoder, carrier, timezone
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn
from rich.text import Text
from rich import box

console = Console()

HEADERS_POOL = [
    {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"},
    {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15"},
    {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"},
]
# ─────────────────────────────────────────────────────────────────────────────
# TRANSLATIONS  (en | el)
# ─────────────────────────────────────────────────────────────────────────────

TRANSLATIONS = {
    "en": {
        "report_title":       "PHONE OSINT INVESTIGATION REPORT v4",
        "generated_by":       "Report generated by phone_osint_v4.py",
        "legal_warning":      "For legal defensive/investigative use only. Unauthorised use may violate GDPR and AVG (Dutch privacy law).",
        "total_checks":       "Total Checks",
        "hits_found":         "Hits Found",
        "no_result":          "No Result",
        "number_analysis":    "Number Analysis",
        "intl_variants_lbl":  "International variants (global dorks)",
        "nat_variants_lbl":   "National variants (scoped dorks only — collision risk)",
        "evidence_title":     "Evidence Checklist",
        "stat_labels": {
            "search":     ("🔍", "Search Engine Dorks"),
            "reputation": ("⭐", "Phone Reputation Databases"),
            "paste":      ("📋", "Paste Site Searches"),
            "social":     ("📱", "Social / Messaging"),
            "api":        ("⚙️",  "API Enrichment"),
        },
        "evidence_items": [
            "Screenshot all threatening messages with timestamps visible",
            "Do NOT delete any messages — they are legal evidence",
            "Note exact date/time of each message received",
            "File a police report — attach this report as evidence",
            "Request a Call Data Record (CDR) from your carrier",
            "Contact the carrier abuse team with screenshots",
            "Only law enforcement can compel the carrier to disclose subscriber identity",
        ],
        "hits":      "hits",
        "url_lbl":   "URL",
        "snippet_lbl": "Snippet",
        "result_lbl":  "Result",
        "report_lbl":  "Report",
        "no_data":   "No data extracted",
    },
    "el": {
        "report_title":       "ΕΚΘΕΣΗ ΕΡΕΥΝΑΣ ΑΡΙΘΜΟΥ ΤΗΛΕΦΩΝΟΥ v4",
        "generated_by":       "Δημιουργήθηκε από phone_osint_v4.py",
        "legal_warning":      "Μόνο για νόμιμη αμυντική/ερευνητική χρήση. Η μη εξουσιοδοτημένη χρήση ενδέχεται να παραβιάζει τον ΓΚΠΔ και τον Νόμο 4624/2019.",
        "total_checks":       "Συνολικοί Έλεγχοι",
        "hits_found":         "Αποτελέσματα",
        "no_result":          "Χωρίς Αποτέλεσμα",
        "number_analysis":    "Ανάλυση Αριθμού",
        "intl_variants_lbl":  "Διεθνείς παραλλαγές (καθολικές αναζητήσεις)",
        "nat_variants_lbl":   "Εθνικές παραλλαγές (μόνο χωρο-εντοπισμένες αναζητήσεις — κίνδυνος σύγκρουσης)",
        "evidence_title":     "Λίστα Ελέγχου Αποδεικτικών Στοιχείων",
        "stat_labels": {
            "search":     ("🔍", "Αναζητήσεις Dork"),
            "reputation": ("⭐", "Βάσεις Φήμης Αριθμού"),
            "paste":      ("📋", "Αναζητήσεις Paste Sites"),
            "social":     ("📱", "Κοινωνικά / Μηνύματα"),
            "api":        ("⚙️",  "Εμπλουτισμός API"),
        },
        "evidence_items": [
            "Στιγμιότυπο όλων των απειλητικών μηνυμάτων με ορατές χρονικές σφραγίδες",
            "ΜΗΝ διαγράψετε κανένα μήνυμα — αποτελούν νομικά αποδεικτικά στοιχεία",
            "Σημειώστε την ακριβή ημερομηνία/ώρα κάθε ληφθέντος μηνύματος",
            "Υποβάλετε καταγγελία στην αστυνομία — επισυνάψτε αυτή την έκθεση",
            "Ζητήστε Αρχείο Δεδομένων Κλήσεων (CDR) από τον πάροχό σας",
            "Επικοινωνήστε με την ομάδα κατάχρησης του παρόχου με στιγμιότυπα",
            "Μόνο οι αρχές επιβολής του νόμου μπορούν να αναγκάσουν τον πάροχο να αποκαλύψει την ταυτότητα συνδρομητή",
        ],
        "hits":      "αποτελέσματα",
        "url_lbl":   "Σύνδεσμος",
        "snippet_lbl": "Απόσπασμα",
        "result_lbl":  "Αποτέλεσμα",
        "report_lbl":  "Αναφορά",
        "no_data":   "Δεν εξήχθησαν δεδομένα",
    },
}



# ─────────────────────────────────────────────────────────────────────────────
# DATA STRUCTURES
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Finding:
    source:    str
    category:  str          # e.g. reputation, social, paste, search, api
    status:    str          # found | not_found | error | skipped
    url:       str = ""
    title:     str = ""
    snippet:   str = ""
    data:      dict = field(default_factory=dict)
    timestamp: str = ""

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.datetime.now().isoformat()

# ─────────────────────────────────────────────────────────────────────────────
# NUMBER PARSING — All format variants
# ─────────────────────────────────────────────────────────────────────────────

def parse_number(raw: str) -> dict:
    try:
        p = phonenumbers.parse(raw, None)
    except phonenumbers.NumberParseException as e:
        console.print(f"[red]❌ Cannot parse: {e}[/red]"); sys.exit(1)

    e164     = phonenumbers.format_number(p, phonenumbers.PhoneNumberFormat.E164)
    intl     = phonenumbers.format_number(p, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
    national = phonenumbers.format_number(p, phonenumbers.PhoneNumberFormat.NATIONAL)
    digits   = ''.join(filter(str.isdigit, e164))
    region   = phonenumbers.region_code_for_number(p)

    type_map = {0:"Fixed Line",1:"Mobile",2:"Fixed or Mobile",3:"Toll Free",
                4:"Premium Rate",5:"Shared Cost",6:"VoIP",7:"Personal",
                8:"Pager",9:"UAN",10:"Voicemail",-1:"Unknown"}

    # ── International variants — include country code, safe to search globally ──
    # These unambiguously identify the number regardless of country context.
    intl_variants = list(dict.fromkeys([
        e164,                        # +31645161166
        intl,                        # +31 6 45161166
        intl.replace(" ", "-"),      # +31-6-45161166
        raw.replace("+", "00"),      # 0031645161166  (legacy 00-prefix)
        digits,                      # 31645161166    (full digits incl. country code)
    ]))

    # ── National variants — NO country code, ONLY safe with country-scoped dorks ──
    # WARNING: These digit strings are ambiguous across countries.
    # e.g. NL national "0645161166" == FR national "0645161166" (+33 6 45161166).
    # NEVER use these in bare global searches — only paired with site:nl or Dutch keywords.
    nat_variants = list(dict.fromkeys([
        national,                        # 06 45161166
        national.replace(" ", ""),       # 0645161166
        national.replace(" ", "-"),      # 06-45161166
        national.replace(" ", "."),      # 06.45161166
    ]))

    return {
        "raw": raw, "e164": e164, "international": intl, "national": national,
        "digits": digits, "region": region,
        "location":      geocoder.description_for_number(p, "en") or "Unknown",
        "carrier":       carrier.name_for_number(p, "en") or "Unknown",
        "timezones":     list(timezone.time_zones_for_number(p)),
        "type":          type_map.get(phonenumbers.number_type(p), "Unknown"),
        "valid":         phonenumbers.is_valid_number(p),
        "global_variants": intl_variants,
        "national_variants": nat_variants,
        "variants": [(v,"global") for v in intl_variants] + [(v,"national-scoped") for v in nat_variants],  # combined for display only
        "country_code":  str(p.country_code),
    }

# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def get(url: str, timeout: int = 10, delay: float = 1.0, headers: dict = None) -> Optional[requests.Response]:
    time.sleep(delay)
    h = headers or HEADERS_POOL[0]
    try:
        r = requests.get(url, headers=h, timeout=timeout, allow_redirects=True)
        return r
    except Exception:
        return None

def soup(r: requests.Response) -> Optional[BeautifulSoup]:
    if r and r.status_code == 200:
        return BeautifulSoup(r.text, "lxml")
    return None

def clean(text: str, maxlen: int = 300) -> str:
    if not text: return ""
    return re.sub(r'\s+', ' ', text.strip())[:maxlen]

# ─────────────────────────────────────────────────────────────────────────────
# MODULE 1 — SEARCH ENGINE DORKS (DuckDuckGo HTML — no API key needed)
# ─────────────────────────────────────────────────────────────────────────────

def build_dork_queries(info: dict) -> list:
    """
    Generate dork queries with strict variant scoping.

    RULE: National variants (no country code) are ONLY used inside country-scoped
    dorks (site:nl, Dutch-language keywords). They are NEVER used in bare global
    searches because the same digit string maps to a different number in another
    country (e.g. NL 0645161166 == FR +33645161166).

    International variants (include country code) are safe for all dorks.
    """
    intl = info["global_variants"]   # safe globally
    nat  = info["national_variants"]  # NL-scoped only

    queries = []

    # ── 1. Bare global exact-match — international variants only ──
    for fmt in intl:
        queries.append(f'"{fmt}"')

    # ── 2. Platform dorks — international variants only ──
    for fmt in intl:
        queries += [
            f'"{fmt}" site:facebook.com',
            f'"{fmt}" site:linkedin.com',
            f'"{fmt}" site:twitter.com OR site:x.com',
            f'"{fmt}" site:reddit.com',
            f'"{fmt}" site:pastebin.com',
            f'"{fmt}" site:truecaller.com',
            f'"{fmt}" spam OR scam OR fraud OR threat OR bedreiging',
            f'"{fmt}" contact OR email OR whatsapp',
            f'"{fmt}" naam OR name OR owner',
            f'"{fmt}" filetype:pdf',
            f'"{fmt}" filetype:xlsx OR filetype:csv',
        ]

    # ── 3. National variants — ONLY with site:nl or Dutch-language keywords ──
    # This prevents cross-country false positives (e.g. matching French numbers).
    for fmt in nat:
        queries += [
            f'"{fmt}" site:nl',
            f'"{fmt}" telefoonnummer site:nl',
            f'"{fmt}" telefoonnummer',
            f'"{fmt}" wie is dit',
            f'"{fmt}" oplichter',
            f'"{fmt}" bedreiging',
            f'"{fmt}" site:facebook.com nl',
            f'"{fmt}" site:marktplaats.nl',
        ]

    return list(dict.fromkeys(queries))  # deduplicate

def scrape_ddg(query: str, delay: float = 1.5) -> list:
    """Scrape DuckDuckGo HTML results for a query."""
    results = []
    encoded = urllib.parse.quote_plus(query)
    url = f"https://html.duckduckgo.com/html/?q={encoded}"
    r = get(url, delay=delay, headers=HEADERS_POOL[2])
    s = soup(r)
    if not s:
        return results
    for result in s.select(".result")[:5]:
        title_el   = result.select_one(".result__title")
        snippet_el = result.select_one(".result__snippet")
        link_el    = result.select_one(".result__url")
        title   = clean(title_el.get_text() if title_el else "")
        snippet = clean(snippet_el.get_text() if snippet_el else "")
        link    = clean(link_el.get_text() if link_el else "")
        if title or snippet:
            results.append({"title": title, "url": link, "snippet": snippet})
    return results

def run_dork_searches(info: dict, delay: float, max_queries: int = 20) -> list:
    findings = []
    queries  = build_dork_queries(info)[:max_queries]

    with Progress(SpinnerColumn(), TextColumn("{task.description}"), BarColumn(), console=console) as prog:
        task = prog.add_task(f"[cyan]Running {len(queries)} dork queries...", total=len(queries))
        for q in queries:
            results = scrape_ddg(q, delay=delay)
            status  = "found" if results else "not_found"
            f = Finding(
                source   = "DuckDuckGo Dork",
                category = "search",
                status   = status,
                url      = f"https://html.duckduckgo.com/html/?q={urllib.parse.quote_plus(q)}",
                title    = q,
                data     = {"query": q, "results": results}
            )
            findings.append(f)
            prog.advance(task)

    return findings

# ─────────────────────────────────────────────────────────────────────────────
# MODULE 2 — PHONE REPUTATION DATABASES
# ─────────────────────────────────────────────────────────────────────────────

def scrape_whocalledme(number: str, delay: float) -> Finding:
    digits = ''.join(filter(str.isdigit, number))
    url    = f"https://whocalledme.com/PhoneNumber/{digits}"
    r      = get(url, delay=delay)
    s      = soup(r)

    if not s:
        return Finding("WhoCalledMe", "reputation", "error", url=url, title="Request failed")

    data = {}
    # Extract rating
    rating = s.select_one(".rating-text, .call-type, h2")
    if rating: data["rating"] = clean(rating.get_text())

    # Extract comments/reports
    comments = s.select(".comment-text, .report-text, p")
    snippets = [clean(c.get_text()) for c in comments[:5] if len(c.get_text().strip()) > 20]
    data["comments"] = snippets

    # Count reports
    count_el = s.select_one(".report-count, .count")
    if count_el: data["report_count"] = clean(count_el.get_text())

    status = "found" if data.get("rating") or snippets else "not_found"
    return Finding("WhoCalledMe", "reputation", status, url=url,
                   snippet=" | ".join(snippets[:2]), data=data)

def scrape_800notes(number_raw: str, delay: float) -> Finding:
    url = f"https://800notes.com/Phone.aspx/{number_raw}"
    r   = get(url, delay=delay)
    s   = soup(r)

    if not s:
        return Finding("800notes", "reputation", "error", url=url)

    data     = {}
    comments = s.select(".msg-body, .comment, p.body")
    snippets = [clean(c.get_text()) for c in comments[:5] if len(c.get_text().strip()) > 20]
    data["comments"] = snippets

    title_el = s.select_one("h1, .phone-title")
    if title_el: data["page_title"] = clean(title_el.get_text())

    status = "found" if snippets else "not_found"
    return Finding("800notes", "reputation", status, url=url,
                   snippet=" | ".join(snippets[:2]), data=data)

def scrape_callername(number: str, delay: float) -> Finding:
    digits = ''.join(filter(str.isdigit, number))
    url    = f"https://www.callername.com/detail/{digits}"
    r      = get(url, delay=delay)
    s      = soup(r)

    if not s:
        return Finding("CallerName.com", "reputation", "error", url=url)

    data    = {}
    name_el = s.select_one(".caller-name, h1, .name")
    if name_el: data["caller_name"] = clean(name_el.get_text())

    type_el = s.select_one(".line-type, .type")
    if type_el: data["line_type"] = clean(type_el.get_text())

    comments = s.select(".comment, p")
    snippets = [clean(c.get_text()) for c in comments[:3] if len(c.get_text().strip()) > 20]
    data["comments"] = snippets

    status = "found" if data.get("caller_name") or snippets else "not_found"
    return Finding("CallerName.com", "reputation", status, url=url,
                   title=data.get("caller_name", ""), data=data)

def scrape_numlookup(number: str, delay: float) -> Finding:
    digits = ''.join(filter(str.isdigit, number))
    url    = f"https://www.numlookup.com/number/{digits}"
    r      = get(url, delay=delay)
    s      = soup(r)

    if not s:
        return Finding("NumLookup.com", "reputation", "error", url=url)

    data = {}
    for row in s.select("table tr, .info-row, .detail-row"):
        cells = row.select("td, th")
        if len(cells) >= 2:
            k = clean(cells[0].get_text())
            v = clean(cells[1].get_text())
            if k and v: data[k] = v

    status = "found" if data else "not_found"
    return Finding("NumLookup.com", "reputation", status, url=url, data=data)

def scrape_spamcalls(number_raw: str, delay: float) -> Finding:
    enc = urllib.parse.quote_plus(number_raw)
    url = f"https://spamcalls.net/en/search?number={enc}"
    r   = get(url, delay=delay)
    s   = soup(r)

    if not s:
        return Finding("SpamCalls.net", "reputation", "error", url=url)

    data     = {}
    comments = s.select(".comment, .report, p")
    snippets = [clean(c.get_text()) for c in comments[:5] if len(c.get_text().strip()) > 20]
    data["comments"] = snippets

    is_spam = any(x in r.text.lower() for x in ["spam", "scam", "fraud", "bedreiging", "threat"])
    data["spam_signals"] = is_spam

    count = r.text.lower().count("report")
    data["report_mentions"] = count

    status = "found" if is_spam or snippets else "not_found"
    return Finding("SpamCalls.net", "reputation", status, url=url,
                   snippet=" | ".join(snippets[:2]), data=data)

# ─────────────────────────────────────────────────────────────────────────────
# MODULE 3 — PASTE SITE SEARCHES
# ─────────────────────────────────────────────────────────────────────────────

def search_pastebin_google(number_variant: str, delay: float) -> Finding:
    q   = f'site:pastebin.com "{number_variant}"'
    enc = urllib.parse.quote_plus(q)
    url = f"https://html.duckduckgo.com/html/?q={enc}"
    r   = get(url, delay=delay, headers=HEADERS_POOL[1])
    s   = soup(r)

    results = []
    if s:
        for res in s.select(".result")[:5]:
            t = res.select_one(".result__title")
            u = res.select_one(".result__url")
            sn = res.select_one(".result__snippet")
            results.append({
                "title":   clean(t.get_text() if t else ""),
                "url":     clean(u.get_text() if u else ""),
                "snippet": clean(sn.get_text() if sn else ""),
            })

    status = "found" if results else "not_found"
    return Finding("Pastebin (via DDG)", "paste", status, url=url,
                   title=f'Searched: {q}', data={"results": results})

def search_paste_sites(info: dict, delay: float) -> list:
    findings = []
    paste_sites = [
        "pastebin.com", "ghostbin.com", "paste.ee",
        "dpaste.com", "hastebin.com", "rentry.co",
    ]
    for variant in info["global_variants"]:  # global only — national variants cause cross-country false positives
        for site in paste_sites[:3]:  # top 3 paste sites
            q   = f'site:{site} "{variant}"'
            enc = urllib.parse.quote_plus(q)
            url = f"https://html.duckduckgo.com/html/?q={enc}"
            r   = get(url, delay=delay, headers=HEADERS_POOL[1])
            s   = soup(r)

            results = []
            if s:
                for res in s.select(".result")[:3]:
                    t  = res.select_one(".result__title")
                    u  = res.select_one(".result__url")
                    sn = res.select_one(".result__snippet")
                    item = {
                        "title":   clean(t.get_text() if t else ""),
                        "url":     clean(u.get_text() if u else ""),
                        "snippet": clean(sn.get_text() if sn else ""),
                    }
                    if item["title"]: results.append(item)

            if results:
                findings.append(Finding(
                    source   = f"Paste: {site}",
                    category = "paste",
                    status   = "found",
                    url      = url,
                    title    = f'"{variant}" on {site}',
                    data     = {"results": results}
                ))

    return findings

# ─────────────────────────────────────────────────────────────────────────────
# MODULE 4 — REDDIT SEARCH
# ─────────────────────────────────────────────────────────────────────────────

def search_reddit(info: dict, delay: float) -> list:
    findings = []
    # Only global variants — Reddit is international, national variants collide
    for variant in info["global_variants"]:  # global only — Reddit is international
        url = f"https://www.reddit.com/search.json?q={urllib.parse.quote(variant)}&limit=10&sort=relevance"
        r   = get(url, delay=delay, headers={"User-Agent": "OSINT-Investigator/4.0"})
        if not r or r.status_code != 200:
            continue
        try:
            j       = r.json()
            posts   = j.get("data", {}).get("children", [])
            results = []
            for post in posts[:5]:
                d = post.get("data", {})
                results.append({
                    "title":     d.get("title", ""),
                    "subreddit": d.get("subreddit_name_prefixed", ""),
                    "url":       f"https://reddit.com{d.get('permalink','')}",
                    "score":     d.get("score", 0),
                    "snippet":   clean(d.get("selftext", "")[:200]),
                })
            if results:
                findings.append(Finding(
                    source   = "Reddit",
                    category = "social",
                    status   = "found",
                    url      = f"https://www.reddit.com/search/?q={urllib.parse.quote(variant)}",
                    title    = f'[GLOBAL] Reddit mentions of {variant}',
                    data     = {"scope": "global", "variant": variant, "posts": results}
                ))
        except Exception:
            pass

    return findings

# ─────────────────────────────────────────────────────────────────────────────
# MODULE 5 — WHATSAPP / TELEGRAM PRESENCE CHECKS
# ─────────────────────────────────────────────────────────────────────────────

def check_messaging_presence(info: dict, delay: float) -> list:
    findings = []
    digits = info["digits"]

    # WhatsApp: wa.me link check
    wa_url = f"https://wa.me/{digits}"
    r = get(wa_url, delay=delay)
    if r:
        # wa.me returns 200 even for non-existent numbers with a specific page
        is_active = r.status_code == 200 and "whatsapp" in r.text.lower()
        findings.append(Finding(
            source   = "WhatsApp (wa.me)",
            category = "social",
            status   = "found" if is_active else "not_found",
            url      = wa_url,
            title    = "WhatsApp presence check",
            snippet  = "Number may have a WhatsApp account" if is_active else "No direct confirmation",
            data     = {"http_status": r.status_code if r else "error"}
        ))

    return findings

# ─────────────────────────────────────────────────────────────────────────────
# MODULE 6 — NUMLOOKUPAPI (free, no key)
# ─────────────────────────────────────────────────────────────────────────────

def api_numlookup(e164: str, delay: float) -> Finding:
    url = f"https://api.numlookupapi.com/v1/info/{urllib.parse.quote(e164)}"
    r   = get(url, delay=delay)
    if not r:
        return Finding("NumLookupAPI", "api", "error", url=url, title="Request failed")
    if r.status_code == 200:
        try:
            d = r.json()
            return Finding("NumLookupAPI", "api", "found", url=url, data={
                "valid":       d.get("valid"),
                "carrier":     d.get("carrier"),
                "line_type":   d.get("line_type"),
                "country":     d.get("country_name"),
                "location":    d.get("location"),
                "local_fmt":   d.get("local_format"),
            })
        except Exception:
            pass
    return Finding("NumLookupAPI", "api", "error", url=url,
                   title=f"HTTP {r.status_code}")

# ─────────────────────────────────────────────────────────────────────────────
# REPORT GENERATORS
# ─────────────────────────────────────────────────────────────────────────────

def save_json(info: dict, findings: list, ts: str, outdir: str) -> str:
    path = os.path.join(outdir, f"phone_osint_{info['digits']}.json")
    # Make variants JSON-serializable (tuples -> dicts)
    info_serializable = {k: v for k, v in info.items()}
    info_serializable["variants"] = [
        {"value": tup[0], "scope": tup[1]}
        for tup in info.get("variants", [])
    ]
    data = {
        "generated":  ts,
        "number_info": info_serializable,
        "findings":    [asdict(f) for f in findings],
        "global_variants": info["global_variants"],
        "national_variants": info["national_variants"],
        "summary": {
            "total":     len(findings),
            "found":     sum(1 for f in findings if f.status == "found"),
            "not_found": sum(1 for f in findings if f.status == "not_found"),
            "errors":    sum(1 for f in findings if f.status == "error"),
        }
    }
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False, default=str)
    return path

def save_html(info: dict, findings: list, ts: str, outdir: str, lang: str = "en") -> str:
    path = os.path.join(outdir, f"phone_osint_{info['digits']}_{lang}.html")
    T = TRANSLATIONS.get(lang, TRANSLATIONS['en'])

    # Group findings by category
    cats  = {}
    for f in findings:
        cats.setdefault(f.category, []).append(f)

    cat_labels = T["stat_labels"]

    def badge(status):
        colors = {"found": "#55ff55", "not_found": "#888", "error": "#ff5555", "skipped": "#ffaa44"}
        c = colors.get(status, "#888")
        return f"<span style='background:#111;color:{c};border:1px solid {c};padding:1px 6px;border-radius:3px;font-size:0.75em;'>{status.upper()}</span>"

    def render_finding(f: Finding) -> str:
        rows = []
        if f.url:
            rows.append(f"<tr><td class='k'>{T['url_lbl']}</td><td><a href='{f.url}' target='_blank'>{f.url[:80]}...</a></td></tr>")
        if f.snippet:
            rows.append(f"<tr><td class='k'>{T['snippet_lbl']}</td><td>{f.snippet}</td></tr>")
        # Render nested data
        for k, v in f.data.items():
            if k == "results" and isinstance(v, list):
                for i, res in enumerate(v[:5], 1):
                    res_url = res.get("url", "")
                    rows.append(f"<tr><td class='k'>{T['result_lbl']} {i}</td><td><b>{res.get('title','')}</b> — {res.get('snippet','')[:120]} <a href='http://{res_url}' target='_blank'>[link]</a></td></tr>")
            elif k == "posts" and isinstance(v, list):
                for post in v[:5]:
                    rows.append(f"<tr><td class='k'>{post.get('subreddit','')}</td><td><a href='{post.get('url','')}' target='_blank'>{post.get('title','')}</a><br><small>{post.get('snippet','')}</small></td></tr>")
            elif k == "comments" and isinstance(v, list):
                for i, c in enumerate(v[:3], 1):
                    if c: rows.append(f"<tr><td class='k'>{T['report_lbl']} {i}</td><td>{c}</td></tr>")
            elif not isinstance(v, (list, dict)):
                rows.append(f"<tr><td class='k'>{k}</td><td>{v}</td></tr>")

        inner = "\n".join(rows) or f"<tr><td colspan='2' style='color:#555'>{T['no_data']}</td></tr>"
        return f"""
<div class='finding {f.status}'>
  <div class='finding-header'>
    <span class='finding-source'>{f.source}</span>
    {badge(f.status)}
    <span class='finding-title'>{f.title[:80]}</span>
  </div>
  <table class='info-table'>{inner}</table>
</div>"""

    body_sections = ""
    for cat, (emoji, label) in cat_labels.items():
        cat_findings = cats.get(cat, [])
        if not cat_findings: continue
        found_ct = sum(1 for f in cat_findings if f.status == "found")
        body_sections += f"<h2>{emoji} {label} <small style='color:#666'>({found_ct}/{len(cat_findings)} {T['hits']})</small></h2>"
        for f in cat_findings:
            body_sections += render_finding(f)

    # Number info table
    info_rows = "".join(
        f"<tr><td class='k'>{k}</td><td>{', '.join(str(x) for x in v) if isinstance(v, list) else v}</td></tr>"
        for k, v in info.items() if k not in ("variants", "global_variants", "national_variants")
    )

    intl_html = " &nbsp; ".join(f"<code style='color:#aaffaa'>{v}</code>" for v in info.get("global_variants", []))
    nat_html  = " &nbsp; ".join(f"<code style='color:#ffcc66'>{v}</code>" for v in info.get("national_variants", []))

    total   = len(findings)
    found_n = sum(1 for f in findings if f.status == "found")

    html = f"""<!DOCTYPE html>
<html lang='{lang}'>
<head>
<meta charset='UTF-8'>
<title>{T['report_title']} — {info['e164']}</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:'Courier New',monospace;background:#080808;color:#ddd;padding:28px;max-width:1200px;margin:auto}}
  h1{{color:#ff2222;font-size:1.6em;border-bottom:2px solid #ff2222;padding-bottom:10px;margin-bottom:10px}}
  h2{{color:#ff6644;margin:28px 0 10px;font-size:1em;text-transform:uppercase;letter-spacing:2px;border-left:3px solid #ff6644;padding-left:8px}}
  .meta{{color:#555;font-size:0.8em;margin-bottom:20px}}
  .warn{{background:#150505;border:1px solid #ff2222;border-radius:4px;padding:10px;color:#ff9999;font-size:0.8em;margin-bottom:20px}}
  .summary{{display:flex;gap:16px;margin-bottom:24px}}
  .stat{{background:#111;border:1px solid #333;border-radius:6px;padding:14px 22px;text-align:center}}
  .stat .n{{font-size:2em;font-weight:bold;color:#ff4444}}
  .stat .l{{font-size:0.75em;color:#888;text-transform:uppercase}}
  .stat.green .n{{color:#44ff88}}
  .info-table{{width:100%;border-collapse:collapse;margin:8px 0 16px}}
  .info-table td{{padding:4px 10px;border:1px solid #1a1a1a;font-size:0.82em}}
  .k{{color:#66aaff;width:180px;background:#0d0d0d}}
  .finding{{background:#0d0d0d;border:1px solid #1e1e1e;border-radius:4px;margin-bottom:10px;overflow:hidden}}
  .finding.found{{border-color:#1a3a1a}}
  .finding.error{{border-color:#1a0000}}
  .finding-header{{background:#111;padding:8px 12px;display:flex;align-items:center;gap:10px;flex-wrap:wrap}}
  .finding-source{{color:#ffaa44;font-weight:bold;font-size:0.85em;min-width:160px}}
  .finding-title{{color:#888;font-size:0.8em;flex:1}}
  a{{color:#66aaff;text-decoration:none}}
  a:hover{{text-decoration:underline}}
  code{{background:#1a1a1a;padding:1px 5px;border-radius:3px;font-size:0.85em;color:#aaffaa}}
  .variants{{margin-bottom:20px;font-size:0.85em}}
</style>
</head>
<body>
<h1>☎ {T['report_title']}</h1>
<div class='meta'>RAVEN Cybersecurity &nbsp;|&nbsp; Generated: {ts} &nbsp;|&nbsp; Target: <strong style='color:#ff6644'>{info['e164']}</strong></div>
<div class='warn'>⚠ {T['legal_warning']}</div>

<div class='summary'>
  <div class='stat'><div class='n'>{total}</div><div class='l'>{T['total_checks']}</div></div>
  <div class='stat green'><div class='n'>{found_n}</div><div class='l'>{T['hits_found']}</div></div>
  <div class='stat'><div class='n'>{total - found_n}</div><div class='l'>{T['no_result']}</div></div>
</div>

<h2>📋 {T['number_analysis']}</h2>
<table class='info-table'>{info_rows}</table>
<div class='variants'>
  <strong style='color:#aaffaa'>🌐 {T['intl_variants_lbl']}</strong>: {intl_html}<br>
  <strong style='color:#ffcc66'>⚠ {T['nat_variants_lbl']}</strong>: {nat_html}
</div>

{body_sections}

<h2>⚖️ {T['evidence_title']}</h2>
<div style='background:#0a1a0a;border:1px solid #1a4a1a;border-radius:4px;padding:16px'>
<ul style='list-style:none'>
{''.join(f"<li style='margin:6px 0;color:#aaffaa;font-size:0.9em'>✔ {item}</li>" for item in T['evidence_items'])}
</ul>
</div>

<div class='meta' style='margin-top:20px'>{T['generated_by']} — RAVEN Cybersecurity</div>
</body>
</html>"""

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html)
    return path

# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Phone OSINT Investigator v3 — RAVEN Cybersecurity"
    )
    parser.add_argument("number",  help="Phone number (E.164 recommended: +31645161166)")
    parser.add_argument("--delay", type=float, default=1.5, help="Delay between requests (default: 1.5s)")
    parser.add_argument("--output", default=".", help="Output directory for reports")
    parser.add_argument("--dorks", type=int, default=15, help="Max dork queries to run (default: 15)")
    parser.add_argument("--lang",  type=str, default="en", choices=["en", "el"],
                        help="Report language: en=English (default), el=Greek")
    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Banner
    t = Text()
    t.append("  ☎  PHONE OSINT INVESTIGATOR v4  ", style="bold red")
    t.append("|  RAVEN Cybersecurity", style="dim white")
    console.print(Panel(t, border_style="red", box=box.DOUBLE_EDGE))
    lang_label = "🇬🇷 Greek" if args.lang == "el" else "🇬🇧 English"
    console.print(f"  [dim]Target: {args.number}  |  {ts}  |  Report language: {lang_label}[/dim]\n")

    # Parse
    info = parse_number(args.number)

    # Print number info
    tbl = Table(title="📋 Number Analysis", box=box.ROUNDED, border_style="cyan", show_header=False)
    tbl.add_column("Field", style="bold cyan", width=22)
    tbl.add_column("Value", style="white")
    skip_keys = {"variants", "global_variants", "national_variants"}
    for k, v in info.items():
        if k in skip_keys:
            continue
        elif isinstance(v, list):
            tbl.add_row(k, ", ".join(str(x) for x in v))
        else:
            tbl.add_row(k, str(v))
    tbl.add_row("[bold green]Global variants[/bold green]",
                "[green]" + " | ".join(info["global_variants"]) + "[/green]")
    tbl.add_row("[bold yellow]National variants[/bold yellow]",
                "[yellow]" + " | ".join(info["national_variants"]) +
                "  ⚠ NL-scoped dorks only[/yellow]")
    console.print(tbl)
    console.print()

    findings = []

    # ── Module 1: Search engine dorks ──
    console.print("[bold yellow]🔍 Running search engine dork queries...[/bold yellow]")
    findings += run_dork_searches(info, args.delay, args.dorks)
    console.print()

    # ── Module 2: Reputation databases ──
    console.print("[bold yellow]⭐ Scraping phone reputation databases...[/bold yellow]")
    rep_tasks = [
        ("WhoCalledMe",  lambda: scrape_whocalledme(info["e164"], args.delay)),
        ("800notes",     lambda: scrape_800notes(info["e164"], args.delay)),
        ("CallerName",   lambda: scrape_callername(info["e164"], args.delay)),
        ("NumLookup",    lambda: scrape_numlookup(info["e164"], args.delay)),
        ("SpamCalls",    lambda: scrape_spamcalls(info["raw"], args.delay)),
    ]
    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console) as prog:
        for name, fn in rep_tasks:
            tid = prog.add_task(f"[cyan]{name}...", total=None)
            f   = fn()
            findings.append(f)
            c   = "green" if f.status == "found" else ("yellow" if f.status == "not_found" else "red")
            prog.update(tid, description=f"[{c}]{name}: {f.status}[/{c}]", completed=True)
    console.print()

    # ── Module 3: Paste sites ──
    console.print("[bold yellow]📋 Searching paste sites...[/bold yellow]")
    paste_findings = search_paste_sites(info, args.delay)
    findings += paste_findings
    console.print(f"  [green]✔ Paste sites:[/green] {len(paste_findings)} hits found")
    console.print()

    # ── Module 4: Reddit ──
    console.print("[bold yellow]💬 Searching Reddit...[/bold yellow]")
    reddit_findings = search_reddit(info, args.delay)
    findings += reddit_findings
    console.print(f"  [green]✔ Reddit:[/green] {len(reddit_findings)} posts found")
    console.print()

    # ── Module 5: Messaging presence ──
    console.print("[bold yellow]📱 Checking messaging app presence...[/bold yellow]")
    msg_findings = check_messaging_presence(info, args.delay)
    findings += msg_findings
    console.print(f"  [green]✔ Messaging:[/green] {len(msg_findings)} checks done")
    console.print()

    # ── Module 6: API ──
    console.print("[bold yellow]⚙️  Running API lookups...[/bold yellow]")
    api_f = api_numlookup(info["e164"], args.delay)
    findings.append(api_f)
    console.print(f"  [green]✔ NumLookupAPI:[/green] {api_f.status}")
    console.print()

    # ── Summary ──
    total   = len(findings)
    found_n = sum(1 for f in findings if f.status == "found")
    console.print(Panel(
        f"[bold white]SCAN COMPLETE[/bold white]\n\n"
        f"  Total checks  : [white]{total}[/white]\n"
        f"  Hits found    : [green]{found_n}[/green]\n"
        f"  No result     : [dim]{total - found_n}[/dim]",
        border_style="yellow", title="📊 Summary", box=box.ROUNDED
    ))
    console.print()

    # ── Save reports ──
    json_path = save_json(info, findings, ts, args.output)
    html_path = save_html(info, findings, ts, args.output, lang=args.lang)

    console.print(f"[bold green]✅ Reports saved:[/bold green]")
    console.print(f"   📄 [white]{json_path}[/white]")
    console.print(f"   🌐 [white]{html_path}[/white]  [dim]← open in browser[/dim]\n")

if __name__ == "__main__":
    main()
